### ISSUE TITLE
Calculation sheet is password protected

### ISSUE THREAD

**Issue by shekhag-zz** [tigormanmsft/az-oracle-sizing#2]
Please note that instead of password protecting the selected cells, the entire calculation sheet is password protected and thus doesn't allow to update DB name, Instance name and Host name,  to determine the final calculation. Therefore, could you please have a look? Thanks, Shekhar.

![image](https://user-images.githubusercontent.com/40043599/139105313-cd9a47e1-61f3-42f1-831f-1e7f51981f29.png)

**Comment by tigormanmsft** [comment]
The default password for the Calculations worksheet is "example".

My apologies, I thought we had that documented;  I'll get that corrected.

Tim Gorman   |   +1 303-885-4526   |   ***@***.******@***.***>
Principal Cloud Solution Architect - Data & AI
Customer Success Architecture & Engineering
[http://mysignature/Templates/Logos/L_Microsoft.png]

From: Shekhar Gupta ***@***.***>
Sent: Wednesday, October 27, 2021 9:15 AM
To: tigormanmsft/az-oracle-sizing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tigormanmsft/az-oracle-sizing] Calculation sheet is password protected (Issue #2)


Please note that instead of password protecting the selected cells, the entire calculation sheet is password protected and thus doesn't allow to update DB name, Instance name and Host name, to determine the final calculation. Therefore, could you please have a look? Thanks, Shekhar.

[Image removed by sender. image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F40043599%2F139105313-cd9a47e1-61f3-42f1-831f-1e7f51981f29.png&data=04%7C01%7CTimothy.Gorman%40microsoft.com%7Ccc426e55ac8c4cd5d34408d99964df8a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637709480813280406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Vf3Ec33Uvl%2FAT4P%2BMES8E4NxlDlSLOHdWsjB5UHzOi0%3D&reserved=0>

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftigormanmsft%2Faz-oracle-sizing%2Fissues%2F2&data=04%7C01%7CTimothy.Gorman%40microsoft.com%7Ccc426e55ac8c4cd5d34408d99964df8a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637709480813290367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6uVcJxMfF5q%2BBWLJ0pyQ%2FqBviZyx98UFin4%2BlE8I%2F2U%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOEEG3PE4HVBOT6XJHJB4W3UJAXP3ANCNFSM5G2X6NKA&data=04%7C01%7CTimothy.Gorman%40microsoft.com%7Ccc426e55ac8c4cd5d34408d99964df8a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637709480813290367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2pP7%2FS1bLbaCeA%2BvMOimN6D3jtNGaKZkB%2FMsyf2EH8g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CTimothy.Gorman%40microsoft.com%7Ccc426e55ac8c4cd5d34408d99964df8a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637709480813290367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8W4MBSvp7CZhh5xfkgGluNk%2B0J%2FdXjfAwRQEtoDb3EU%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CTimothy.Gorman%40microsoft.com%7Ccc426e55ac8c4cd5d34408d99964df8a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637709480813300320%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JxOUHfl5UN5MSvTB20%2BiFg48n%2FHY1OfzeRoTk3R4EPk%3D&reserved=0>.

**Comment by shekhag-zz** [comment]
Hi Tim, Thanks for the quick assistance😊
